name: example
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  gradient_widgets:
    path: ../
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_driver:
    sdk: flutter
  test: any

flutter:

  uses-material-design: true
