name: gradient_widgets
description: A minimal set of Flutter widgets encased with beautiful gradients.
version: 0.6.0
homepage: https://github.com/bluemix/gradient-widgets

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

